spring:
  profiles:
    active: development

server:
  port: 8888


limits:
  relative:
    buyDiff: 0.05
    sellDiff: 0.04
    supplyAndDemandDiff: 0.02
  fixed:
    buyDiff: 250
    sellDiff: 150
    supplyAndDemandDiff: 250

---
spring:
  profiles: development
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: bitcoin


---
spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: bitcoin

server:
  port: 80
